"""Autonomous reasoning loop for iterative UI task execution."""

from __future__ import annotations

import io
import json
import math
from pathlib import Path
import re
import shlex
import shutil
import subprocess
import tempfile
import time
from urllib.parse import quote_plus
import webbrowser
from dataclasses import dataclass, field
from queue import Empty
from typing import Any, Dict, List, Optional, Tuple

from PIL import Image

from .automator import UIAutomator
from .config import Config
from .runtime import AgentRuntime
from .utils import get_screenshot_bytes_and_dims, toggle_screen_privacy
from .vision import VisionAnalyzer


@dataclass
class ActionPlan:
    """Single action generated by LLM planner."""

    action: str
    target: str = ""
    text: str = ""
    url: str = ""
    app: str = ""
    shell: str = ""
    seconds: float = 1.0
    keys: List[str] = field(default_factory=list)
    key: str = ""
    reason: str = ""


class AgentBrain:
    """Plans and executes step-by-step actions until the goal is complete."""

    def __init__(self, runtime: AgentRuntime, config: Optional[Config] = None) -> None:
        self.runtime = runtime
        self.config = config or Config()
        self.automator = UIAutomator()
        self.analyzer = VisionAnalyzer(
            self.config.get_api_key(),
            model_name=self.config.gemini_model,
        )
        self.screen_privacy_enabled = self.config.screen_privacy

    def run_command_worker(self, stop_event) -> None:
        """Background worker that consumes commands from TUI and web."""
        self.runtime.add_log("info", "Command worker started")
        while not stop_event.is_set():
            try:
                command = self.runtime.command_queue.get(timeout=0.2)
            except Empty:
                continue

            if not command:
                continue

            self.runtime.add_chat(
                "user",
                command,
                kind="user_text",
                structured={
                    "type": "user_input",
                    "status": "ok",
                    "message": command,
                    "data": {},
                },
            )
            lower = command.lower().strip()

            if lower in {"quit", "exit", "/quit", "/exit"}:
                self._emit_assistant_output(
                    "system",
                    "success",
                    "Shutdown requested.",
                )
                self.runtime.add_log("info", "Shutdown command received")
                stop_event.set()
                return

            if lower.startswith("/privacy"):
                self._handle_privacy_command(command)
                continue

            direct_control = self._try_direct_manual_control(command)
            if direct_control is not None:
                msg, status, data = direct_control
                self._emit_assistant_output("task", status, msg, data)
                continue

            if lower.startswith("vision") or "what do you see" in lower:
                question = command.split(":", 1)[1].strip() if ":" in command else command
                answer = self.describe_screen(question)
                self._emit_assistant_output(
                    "vision",
                    "success" if not answer.lower().startswith("vision chat failed:") else "error",
                    answer,
                    {"question": question},
                )
                continue

            if self._is_chat_request(command):
                answer = self.chat(command)
                self._emit_assistant_output(
                    "chat",
                    "success" if not answer.lower().startswith("chat failed:") else "error",
                    answer,
                    {"mode": "chat"},
                )
                continue

            direct_store = self._try_direct_app_store_task(command)
            if direct_store is not None:
                msg, status, data = direct_store
                data = self._finalize_task_data(command, status, data, msg)
                self._emit_assistant_output("task", status, msg, data)
                continue

            direct_editor = self._try_direct_text_editor_task(command)
            if direct_editor is not None:
                msg, status, data = direct_editor
                data = self._finalize_task_data(command, status, data, msg)
                self._emit_assistant_output("task", status, msg, data)
                continue

            direct_browser = self._try_direct_browser_task(command)
            if direct_browser is not None:
                msg, status, data = direct_browser
                data = self._finalize_task_data(command, status, data, msg)
                self._emit_assistant_output("task", status, msg, data)
                continue

            direct_calc = self._try_direct_calculator_task(command)
            if direct_calc is not None:
                msg, status, data = direct_calc
                data = self._finalize_task_data(command, status, data, msg)
                self._emit_assistant_output("task", status, msg, data)
                continue

            direct_launch = self._try_direct_launch(command)
            if direct_launch is not None:
                success = direct_launch.lower().startswith("opened") or direct_launch.lower().startswith("launched")
                status = "success" if success else "error"
                data = self._finalize_task_data(
                    command,
                    status,
                    {"mode": "direct_launch", "goal": command},
                    direct_launch,
                )
                self._emit_assistant_output(
                    "task",
                    status,
                    direct_launch,
                    data,
                )
                continue

            result = self.run_goal(command)
            status = "success" if result.lower().startswith("goal completed") else "incomplete"
            data = self._finalize_task_data(
                command,
                status,
                {"mode": "automation", "goal": command},
                result,
            )
            self._emit_assistant_output(
                "task",
                status,
                result,
                data,
            )

    def _emit_assistant_output(
        self,
        output_type: str,
        status: str,
        message: str,
        data: Optional[Dict[str, Any]] = None,
    ) -> None:
        payload = {
            "type": output_type,
            "status": status,
            "message": message,
            "data": data or {},
        }
        self.runtime.add_chat(
            "assistant",
            message,
            kind="structured_output",
            structured=payload,
        )

    def _enrich_with_visual_insight(self, data: Dict[str, Any], goal: str, status: str) -> Dict[str, Any]:
        """Attach a short screenshot-based observation for successful task actions."""
        if status != "success":
            return data

        enriched = dict(data)
        observation = self._capture_visual_observation(goal)
        enriched["observation"] = observation
        return enriched

    def _finalize_task_data(self, goal: str, status: str, data: Dict[str, Any], message: str) -> Dict[str, Any]:
        enriched = self._enrich_with_visual_insight(data, goal, status)
        mode = str(enriched.get("mode", "task"))
        if not isinstance(enriched.get("steps"), list):
            enriched["steps"] = [
                f"received: {goal}",
                f"routed: {mode}",
                f"result: {status}",
                f"message: {message}",
            ]
        if "current_screen" not in enriched:
            enriched["current_screen"] = enriched.get("observation", "")
        return enriched

    def _capture_visual_observation(self, goal: str) -> str:
        """Describe what is currently visible after a task to provide user insight."""
        try:
            screenshot_bytes, _, _ = self._safe_screenshot()
            prompt = (
                "You are validating a desktop automation result. "
                f"Goal: {goal}\n"
                "In one concise sentence, describe what is currently visible and whether it appears successful."
            )
            answer = self._ask_vision(prompt, screenshot_bytes)
            text = (answer or "").strip()
            if text:
                return text
            return "Observation unavailable: vision model returned an empty description."
        except Exception as exc:
            reason = str(exc).strip() or "unknown error"
            self.runtime.add_log("warning", f"Visual insight unavailable: {reason}")
            return f"Observation unavailable: {reason}"

    def _try_direct_manual_control(self, command: str) -> Optional[Tuple[str, str, Dict[str, Any]]]:
        """Direct human-like control path: mouse move/click + keyboard typing/keys/hotkeys."""
        raw = command.strip()
        lowered = raw.lower()

        # Use explicit mode only to avoid hijacking natural-language tasks.
        if not lowered.startswith("do:"):
            return None

        sequence = raw[3:].strip()
        if not sequence:
            return (
                "Manual mode is empty. Example: do: move mouse to 500 300; click; type hello; press enter",
                "info",
                {"mode": "direct_manual_control", "goal": command, "steps": []},
            )

        # Split chained actions: "then" or semicolons.
        actions = [a.strip() for a in re.split(r"\s+then\s+|;", sequence, flags=re.IGNORECASE) if a.strip()]
        if not actions:
            return None

        done_steps: List[str] = []
        try:
            for idx, action in enumerate(actions, start=1):
                step = self._execute_manual_action(action)
                done_steps.append(step)
                self.runtime.add_log("info", f"Manual control step {idx}: {step}")

            summary = "Executed manual controls successfully."
            return (
                summary,
                "success",
                {
                    "mode": "direct_manual_control",
                    "goal": command,
                    "steps": done_steps,
                },
            )
        except Exception as exc:
            err = f"Manual control failed: {exc}"
            self.runtime.add_log("error", err)
            return (
                err,
                "error",
                {
                    "mode": "direct_manual_control",
                    "goal": command,
                    "steps": done_steps,
                },
            )

    def _execute_manual_action(self, action: str) -> str:
        text = action.strip()
        lower = text.lower()

        # move mouse to X Y
        m_move = re.match(r"^(?:move mouse to|mouse move to|move to)\s+(\d+)\s*[ ,]\s*(\d+)$", lower)
        if m_move:
            x, y = int(m_move.group(1)), int(m_move.group(2))
            self.automator.move_mouse(x, y)
            return f"move_mouse({x}, {y})"

        # click [x y]
        m_click = re.match(r"^click(?:\s+(\d+)\s*[ ,]\s*(\d+))?$", lower)
        if m_click:
            if m_click.group(1) and m_click.group(2):
                x, y = int(m_click.group(1)), int(m_click.group(2))
                self.automator.click_at(x, y)
                return f"click_at({x}, {y})"
            self.automator.click_current_position()
            return "click_current()"

        # type ...
        m_type = re.match(r"^type\s+(.+)$", text, flags=re.IGNORECASE)
        if m_type:
            payload = m_type.group(1).strip()
            if (payload.startswith('"') and payload.endswith('"')) or (payload.startswith("'") and payload.endswith("'")):
                payload = payload[1:-1]
            self.automator.type_text_unicode(payload, interval=0.02, delay=0.05)
            return f"type({len(payload)} chars)"

        # press key
        m_press = re.match(r"^press\s+([a-z0-9_\-]+)$", lower)
        if m_press:
            key = m_press.group(1)
            self.automator.press_key(key)
            return f"press({key})"

        # hotkey ctrl+l / hotkey ctrl shift s
        m_hotkey = re.match(r"^hotkey\s+(.+)$", text, flags=re.IGNORECASE)
        if m_hotkey:
            raw_keys = m_hotkey.group(1).strip()
            keys = [k.strip().lower() for k in re.split(r"\+|\s+", raw_keys) if k.strip()]
            if not keys:
                raise ValueError("Hotkey requires at least one key")
            self.automator.send_hotkey(tuple(keys))
            return f"hotkey({'+'.join(keys)})"

        # wait seconds
        m_wait = re.match(r"^wait\s+([0-9]+(?:\.[0-9]+)?)$", lower)
        if m_wait:
            seconds = float(m_wait.group(1))
            time.sleep(max(0.05, min(seconds, 10.0)))
            return f"wait({seconds:g}s)"

        raise ValueError(
            "Unsupported manual action. Use: move mouse to X Y, click [X Y], type ..., press KEY, hotkey ..., wait S"
        )

    def _try_direct_calculator_task(self, command: str) -> Optional[Tuple[str, str, Dict[str, Any]]]:
        """Fast path for calculator workflows like 'open calculator and add 8+5'."""
        lower = command.lower().strip()
        lower = re.sub(r"^task:\s*", "", lower)

        # Only handle commands clearly about calculator math workflows.
        has_calc = "calculator" in lower or re.search(r"\bcalc\b", lower) is not None
        has_math_intent = re.search(r"\b(add|plus|sum|calculate|compute|subtract|multiply|divide)\b", lower) is not None
        has_expression = self._extract_math_expression(lower) is not None
        if not has_calc or (not has_math_intent and not has_expression):
            return None

        launch_msg = self._try_direct_launch("open calculator")
        if launch_msg is None or launch_msg.lower().startswith("could not"):
            return (
                launch_msg or "Could not launch calculator.",
                "error",
                {"mode": "direct_calculator", "goal": command},
            )

        expr = self._extract_math_expression(lower)
        if not expr:
            return (
                "Launched calculator. Please include an expression, for example: `open calculator and add 8+5`.",
                "info",
                {"mode": "direct_calculator", "goal": command},
            )

        try:
            # Give the app a moment to focus before typing.
            time.sleep(0.45)
            self.automator.type_text_unicode(expr, interval=0.03, delay=0.1)
            self.automator.press_key("enter")
            result = self._safe_eval_expression(expr)
            if result is None:
                msg = f"Launched calculator and entered `{expr}`."
            else:
                msg = f"Launched calculator and entered `{expr}`. Result: `{result}`."
            self.runtime.add_log("success", msg)
            return (
                msg,
                "success",
                {"mode": "direct_calculator", "goal": command, "expression": expr},
            )
        except Exception as exc:
            err_msg = f"Launched calculator, but could not type expression `{expr}`: {exc}"
            self.runtime.add_log("error", err_msg)
            return (
                err_msg,
                "error",
                {"mode": "direct_calculator", "goal": command, "expression": expr},
            )

    def _extract_math_expression(self, text: str) -> Optional[str]:
        """Extract a simple arithmetic expression from user text."""
        normalized = text.replace("x", "*")
        match = re.search(r"(-?\d+(?:\.\d+)?(?:\s*[+\-*/]\s*-?\d+(?:\.\d+)?)+)", normalized)
        if not match:
            return None
        expr = re.sub(r"\s+", "", match.group(1))
        if re.fullmatch(r"[-+*/().\d]+", expr) is None:
            return None
        return expr

    def _safe_eval_expression(self, expr: str) -> Optional[str]:
        """Safely evaluate very simple math expressions for feedback text."""
        if re.fullmatch(r"[-+*/().\d]+", expr or "") is None:
            return None
        try:
            value = eval(expr, {"__builtins__": {}}, {})  # nosec - guarded by strict regex
            if isinstance(value, (int, float)):
                if isinstance(value, float) and math.isfinite(value):
                    return f"{value:g}"
                if isinstance(value, int):
                    return str(value)
            return None
        except Exception:
            return None

    def _try_direct_browser_task(self, command: str) -> Optional[Tuple[str, str, Dict[str, Any]]]:
        """Fast path for browser search workflows like 'open browser and search cats'."""
        lower = command.lower().strip()
        lower = re.sub(r"^task:\s*", "", lower)

        has_browser = re.search(r"\b(browser|firefox|chrome|chromium)\b", lower) is not None
        has_search = "search" in lower
        has_web_intent = re.search(r"\b(google|web|internet|website|url|online|browse)\b", lower) is not None
        has_appstore_intent = re.search(r"\b(app store|cosmic store|software center|store app|marketplace)\b", lower) is not None

        # Prevent browser shortcut from hijacking non-web store commands.
        if has_appstore_intent:
            return None

        # Run only when there is both search intent and explicit web/browser intent.
        if not (has_search and (has_browser or has_web_intent)):
            return None

        query = self._extract_search_query(lower)
        if not query:
            if has_browser and has_search:
                return (
                    "Opened browser task detected, but search text is missing. Example: `open browser and search python tutorials`.",
                    "info",
                    {"mode": "direct_browser_search", "goal": command},
                )
            return None

        launch_msg = self._try_direct_launch("open browser")
        if launch_msg is None or launch_msg.lower().startswith("could not"):
            return (
                launch_msg or "Could not open browser.",
                "error",
                {"mode": "direct_browser_search", "goal": command, "query": query},
            )

        url = f"https://www.google.com/search?q={quote_plus(query)}"
        opened = self._try_direct_launch(f"open {url}")
        if opened and not opened.lower().startswith("could not"):
            msg = f"Opened browser and searched Google for `{query}`."
            self.runtime.add_log("success", msg)
            return (
                msg,
                "success",
                {"mode": "direct_browser_search", "goal": command, "query": query, "url": url},
            )

        err = opened or "Could not open search URL."
        return (
            f"Opened browser, but search navigation failed: {err}",
            "error",
            {"mode": "direct_browser_search", "goal": command, "query": query, "url": url},
        )

    def _try_direct_app_store_task(self, command: str) -> Optional[Tuple[str, str, Dict[str, Any]]]:
        """Fast path for app-store workflows like 'open cosmic app store and search for vscode'."""
        lower = command.lower().strip()
        lower = re.sub(r"^task:\s*", "", lower)

        has_store = re.search(r"\b(app store|cosmic store|software center|store app)\b", lower) is not None
        if not has_store:
            return None

        query = self._extract_search_query(lower)
        launch_msg = self._try_direct_launch("open cosmic app store") or self._try_direct_launch("open app store")
        if launch_msg is None or launch_msg.lower().startswith("could not"):
            return (
                launch_msg or "Could not open app store.",
                "error",
                {"mode": "direct_app_store", "goal": command},
            )

        if not query:
            return (
                "Launched app store. Tell me what to search, for example: `open cosmic app store and search for firefox`.",
                "info",
                {"mode": "direct_app_store", "goal": command},
            )

        # Prefer native CLI search arguments when available (most reliable path).
        cli_search = self._try_direct_app_store_cli_search(query)
        if cli_search is not None:
            msg, status = cli_search
            self.runtime.add_log(status if status in {"success", "error"} else "info", msg)
            return (
                msg,
                status,
                {"mode": "direct_app_store", "goal": command, "query": query, "strategy": "cli"},
            )

        try:
            # Give app store time to open and attempt common search shortcuts.
            time.sleep(1.0)
            # Avoid Alt+Tab because it can land on another app/window.
            for hotkey in (("ctrl", "l"), ("ctrl", "k"), ("ctrl", "f"), ("slash",)):
                if hotkey == ("slash",):
                    self.automator.press_key("/")
                else:
                    self.automator.send_hotkey(hotkey)
                time.sleep(0.12)
                self.automator.send_hotkey(("ctrl", "a"))
                self.automator.press_key("backspace")
                self.automator.type_text_unicode(query, interval=0.03, delay=0.02)
                self.automator.press_key("enter")
                time.sleep(0.08)
            msg = f"Opened app store and searched for `{query}`."
            self.runtime.add_log("success", msg)
            return (
                msg,
                "success",
                {"mode": "direct_app_store", "goal": command, "query": query},
            )
        except Exception as exc:
            err = f"Opened app store, but could not type search `{query}`: {exc}"
            self.runtime.add_log("error", err)
            return (
                err,
                "error",
                {"mode": "direct_app_store", "goal": command, "query": query},
            )

    def _try_direct_app_store_cli_search(self, query: str) -> Optional[Tuple[str, str]]:
        """Try launching app store directly with query arguments.

        Returns tuple of (message, status) or None if no supported binary is available.
        """
        normalized = query.strip()
        if not normalized:
            return None

        attempts: List[List[str]] = []

        if shutil.which("cosmic-store"):
            attempts.extend(
                [
                    ["cosmic-store", "--search", normalized],
                    ["cosmic-store", normalized],
                ]
            )
        if shutil.which("gnome-software"):
            attempts.extend(
                [
                    ["gnome-software", f"--search={normalized}"],
                    ["gnome-software", "--search", normalized],
                ]
            )
        if shutil.which("plasma-discover"):
            attempts.append(["plasma-discover", "--search", normalized])

        if not attempts:
            return None

        last_error = ""
        for cmd in attempts:
            try:
                proc = subprocess.Popen(cmd, stdout=subprocess.PIPE, stderr=subprocess.PIPE, text=True)
                time.sleep(0.35)
                rc = proc.poll()
                if rc is None or rc == 0:
                    return (f"Opened app store search for `{normalized}`.", "success")
                stderr = (proc.stderr.read() or "").strip() if proc.stderr else ""
                if stderr:
                    last_error = stderr[:220]
            except Exception as exc:
                last_error = str(exc)

        if last_error:
            return (f"CLI app-store search failed: {last_error}", "error")
        return ("CLI app-store search failed.", "error")

    def _try_direct_text_editor_task(self, command: str) -> Optional[Tuple[str, str, Dict[str, Any]]]:
        """Fast path for text editor workflows like 'open text editor and type a paragraph'."""
        lower = command.lower().strip()
        lower = re.sub(r"^task:\s*", "", lower)

        has_editor = re.search(r"\b(text editor|editor|notepad|gedit|kate|code)\b", lower) is not None
        has_type_intent = "type" in lower
        if not (has_editor and has_type_intent):
            return None

        text = self._extract_editor_text(command)
        if not text:
            return (
                "Launched text editor. Tell me what to type.",
                "info",
                {"mode": "direct_text_editor", "goal": command},
            )

        try:
            file_path = self._write_temp_text_file(text)
            opened, strategy = self._open_text_file_in_editor(file_path)
            if not opened:
                return (
                    "Could not open a text editor with the generated paragraph file.",
                    "error",
                    {"mode": "direct_text_editor", "goal": command},
                )

            msg = f"Opened text editor with paragraph file ({len(text)} chars)."
            self.runtime.add_log("success", msg)
            return (
                msg,
                "success",
                {
                    "mode": "direct_text_editor",
                    "goal": command,
                    "chars": len(text),
                    "preview": text[:80],
                    "file": str(file_path),
                    "strategy": strategy,
                },
            )
        except Exception as exc:
            err = f"Opened text editor, but typing failed: {exc}"
            self.runtime.add_log("error", err)
            return (
                err,
                "error",
                {"mode": "direct_text_editor", "goal": command},
            )

    def _extract_editor_text(self, command: str) -> str:
        lower = command.lower()
        if "type a paragraph" in lower:
            return (
                "This is a sample paragraph typed by Slovio. It demonstrates direct desktop automation "
                "by opening a text editor, focusing the window, and entering readable text without "
                "using the slower vision planning loop."
            )

        match = re.search(r"type\s+(.+)$", command, re.IGNORECASE)
        if not match:
            return ""
        text = match.group(1).strip().strip(". ")
        return text

    def _write_temp_text_file(self, text: str) -> Path:
        fd, path = tempfile.mkstemp(prefix="slovio-note-", suffix=".txt")
        with open(fd, "w", encoding="utf-8", closefd=True) as handle:
            handle.write(text)
            handle.write("\n")
        return Path(path)

    def _open_text_file_in_editor(self, file_path: Path) -> Tuple[bool, str]:
        candidates: List[Tuple[List[str], str]] = [
            (["cosmic-edit", str(file_path)], "cosmic-edit"),
            (["gedit", str(file_path)], "gedit"),
            (["kate", str(file_path)], "kate"),
            (["mousepad", str(file_path)], "mousepad"),
            (["pluma", str(file_path)], "pluma"),
            (["xed", str(file_path)], "xed"),
            (["leafpad", str(file_path)], "leafpad"),
            (["xdg-open", str(file_path)], "xdg-open"),
            (["code", "--new-window", str(file_path)], "code"),
        ]

        for cmd, strategy in candidates:
            if not shutil.which(cmd[0]):
                continue
            try:
                proc = subprocess.Popen(cmd, stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
                time.sleep(0.3)
                rc = proc.poll()
                if rc is None or rc == 0:
                    return True, strategy
            except Exception:
                continue
        return False, "none"

    def _extract_search_query(self, text: str) -> Optional[str]:
        m = re.search(r"search(?:\s+for)?\s+(.+)$", text)
        if not m:
            return None
        query = m.group(1).strip()
        query = re.sub(r"\s+on\s+google$", "", query).strip()
        query = query.strip(".?!")
        return query or None

    def _try_direct_launch(self, command: str) -> Optional[str]:
        """Fast path for simple `open X` / `launch X` commands without vision loop."""
        lower = command.lower().strip()
        lower = re.sub(r"^task:\s*", "", lower)
        match = re.match(r"^(open|launch)\s+(?:the\s+)?(.+)$", lower)
        if not match:
            return None

        target = match.group(2).strip().strip(".?!")
        # Keep multi-step commands in the autonomous planner.
        if any(token in target for token in (" and ", " then ", " after ", " before ", " type ", " click ")):
            return None

        if target.startswith(("http://", "https://")):
            try:
                webbrowser.open(target)
                self.runtime.add_log("info", f"Opened URL directly: {target}")
                return f"Opened {target}."
            except Exception as exc:
                self.runtime.add_log("error", f"Direct URL open failed: {exc}")
                return f"Could not open {target}: {exc}"

        candidates = self._launch_candidates_for_target(target)
        last_error = ""
        for cmd in candidates:
            ok, err = self._launch_command_with_quick_check(cmd)
            if ok:
                self.runtime.add_log("success", f"Direct launch succeeded: {cmd}")
                return f"Launched {target}."
            last_error = err or last_error

        message = f"Could not launch {target}."
        if last_error:
            message += f" {last_error}"
        self.runtime.add_log("error", message)
        return message

    def _launch_candidates_for_target(self, target: str) -> List[str]:
        target = target.strip()

        presets = {
            "calculator": ["gnome-calculator", "kcalc", "xcalc", "qalculate-gtk"],
            "calc": ["gnome-calculator", "kcalc", "xcalc", "qalculate-gtk"],
            "browser": ["xdg-open https://www.google.com", "firefox", "google-chrome", "chromium"],
            "firefox": ["firefox"],
            "chrome": ["google-chrome", "chromium"],
            "text editor": ["gedit", "kate", "mousepad", "pluma", "xed", "leafpad", "cosmic-edit", "code --new-window"],
            "bluetooth manager": [
                "blueman-manager",
                "gnome-control-center bluetooth",
                "kcmshell6 kcm_bluetooth",
                "kcmshell5 kcm_bluetooth",
                "mate-bluetooth-properties",
                "xfce4-settings-manager",
            ],
            "bluetooth": [
                "blueman-manager",
                "gnome-control-center bluetooth",
                "kcmshell6 kcm_bluetooth",
                "kcmshell5 kcm_bluetooth",
            ],
            "terminal": ["gnome-terminal", "konsole", "xfce4-terminal", "xterm", "kitty", "alacritty"],
            "files": ["xdg-open .", "nautilus", "thunar", "dolphin", "pcmanfm"],
            "cosmic app store": ["cosmic-store", "flatpak run com.system76.CosmicStore", "gnome-software"],
            "app store": ["cosmic-store", "gnome-software", "plasma-discover", "pamac-manager"],
            "software center": ["gnome-software", "plasma-discover", "pamac-manager"],
        }

        if target in presets:
            return presets[target]

        # Generic fallback: try literal target as command first, then xdg-open.
        return [target, f"xdg-open {shlex.quote(target)}"]

    def _launch_command_with_quick_check(self, cmd: str) -> Tuple[bool, str]:
        try:
            proc = subprocess.Popen(
                shlex.split(cmd),
                stdout=subprocess.PIPE,
                stderr=subprocess.PIPE,
                text=True,
            )
            time.sleep(0.35)
            rc = proc.poll()
            if rc is None:
                return True, ""
            if rc == 0:
                return True, ""
            stderr = (proc.stderr.read() or "").strip() if proc.stderr else ""
            return False, stderr[:220]
        except FileNotFoundError:
            return False, "Command not found"
        except Exception as exc:
            return False, str(exc)

    def _handle_privacy_command(self, command: str) -> None:
        lower = command.lower().strip()
        if " on" in lower:
            self.screen_privacy_enabled = True
            self.runtime.add_log("info", "Screen privacy mode enabled")
            self._emit_assistant_output("system", "success", "Screen privacy mode enabled.")
            return
        if " off" in lower:
            self.screen_privacy_enabled = False
            self.runtime.add_log("info", "Screen privacy mode disabled")
            self._emit_assistant_output("system", "success", "Screen privacy mode disabled.")
            return
        status = "on" if self.screen_privacy_enabled else "off"
        self._emit_assistant_output(
            "system",
            "info",
            f"Screen privacy mode is {status}. Use /privacy on or /privacy off.",
        )

    def _is_chat_request(self, command: str) -> bool:
        lower = command.lower().strip()
        if lower.startswith("chat:"):
            return True

        # Explicit task mode.
        if lower.startswith("task:"):
            return False

        # Treat as automation only when user clearly asks for desktop actions.
        task_starters = (
            "open ",
            "launch ",
            "click ",
            "type ",
            "press ",
            "go to ",
            "navigate ",
            "fill ",
            "search ",
            "scroll ",
            "drag ",
            "drop ",
            "switch ",
            "close ",
            "maximize ",
            "minimize ",
            "run ",
            "execute ",
        )
        if lower.startswith(task_starters):
            return False

        if re.search(r"\b(open|launch|click|type|press|navigate|go to|run|execute)\b", lower):
            if re.search(r"\b(browser|firefox|chrome|calculator|terminal|app|window|tab|url|website)\b", lower):
                return False

        # Default behavior: act like a normal chat assistant.
        return True

    def chat(self, prompt: str) -> str:
        """General chat mode, like a normal LLM assistant."""
        try:
            response = self.analyzer.model.generate_content(
                [
                    "You are Slovio, a concise and practical assistant for desktop users.",
                    prompt,
                ]
            )
            maybe_raise = getattr(response, "raise_for_exception", None)
            if callable(maybe_raise):
                maybe_raise()
            text = (response.text or "").strip()
            return text or "I could not generate a response right now."
        except Exception as exc:
            message = f"Chat failed: {exc}"
            self.runtime.add_log("error", message)
            return message

    def run_goal(self, goal: str, max_steps: Optional[int] = None) -> str:
        """Execute think->act->verify loop until goal is satisfied or steps are exhausted."""
        max_steps = max_steps or self.config.max_task_steps
        self.runtime.reset_steps()
        self.runtime.set_status("running", goal=goal)
        self.runtime.add_log("info", f"Goal started: {goal}")

        privacy_was_applied = False
        if self.screen_privacy_enabled:
            ok, msg = toggle_screen_privacy(blank=True)
            if ok:
                privacy_was_applied = True
                self.runtime.add_log("info", f"Privacy mode active: {msg}")
            else:
                self.runtime.add_log("warning", f"Could not enable privacy mode: {msg}")

        try:
            for step_idx in range(1, max_steps + 1):
                try:
                    before_png, screen_w, screen_h = self._safe_screenshot()
                    self.runtime.set_screenshot(before_png)
                    self.runtime.increment_step()
                    self.runtime.add_log("info", f"Step {step_idx}: planning next action")

                    plan = self._plan_action(goal, before_png)
                    self.runtime.add_log(
                        "info",
                        f"Step {step_idx}: action={plan.action}",
                        {
                            "action": plan.action,
                            "target": plan.target,
                            "text": plan.text,
                            "url": plan.url,
                            "app": plan.app,
                            "shell": plan.shell,
                            "key": plan.key,
                            "keys": plan.keys,
                        },
                    )

                    if plan.action == "finish":
                        self.runtime.set_status("idle")
                        message = plan.reason or "Goal completed"
                        self.runtime.add_log("success", message)
                        return message

                    if plan.action == "fail":
                        self.runtime.set_status("idle")
                        message = plan.reason or "Planner reported failure"
                        self.runtime.add_log("error", message)
                        return message

                    self._execute_action(plan, screen_w, screen_h, before_png)

                    after_png, _, _ = self._safe_screenshot()
                    self.runtime.set_screenshot(after_png)

                    if self._goal_is_met(goal, after_png):
                        self.runtime.set_status("idle")
                        self.runtime.add_log("success", f"Goal completed at step {step_idx}")
                        return f"Goal completed in {step_idx} step(s)."

                except Exception as exc:
                    self.runtime.add_log("error", f"Step {step_idx} error: {exc}")
                    if "display" in str(exc).lower() or "x11" in str(exc).lower() or "wayland" in str(exc).lower():
                        self.runtime.add_log(
                            "error",
                            "Display backend issue detected (Wayland/X11). Ensure GUI access and DISPLAY/WAYLAND_DISPLAY are configured.",
                        )
                    time.sleep(0.4)
        finally:
            if privacy_was_applied:
                ok, msg = toggle_screen_privacy(blank=False)
                if ok:
                    self.runtime.add_log("info", f"Privacy mode disabled: {msg}")
                else:
                    self.runtime.add_log("warning", f"Could not restore screen from privacy mode: {msg}")

        self.runtime.set_status("idle")
        self.runtime.add_log("warning", "Goal not completed within max steps")
        return "Goal not completed within the current step limit."

    def describe_screen(self, question: str = "What do you see on my screen?") -> str:
        """Vision chat endpoint that describes current screen content."""
        try:
            screenshot_bytes, _, _ = self._safe_screenshot()
            self.runtime.set_screenshot(screenshot_bytes)
            answer = self._ask_vision(question, screenshot_bytes)
            self.runtime.add_log("info", "Vision chat completed")
            return answer
        except Exception as exc:
            message = f"Vision chat failed: {exc}"
            self.runtime.add_log("error", message)
            return message

    def _safe_screenshot(self):
        try:
            return get_screenshot_bytes_and_dims()
        except Exception as exc:
            msg = str(exc)
            if "display" in msg.lower() or "x11" in msg.lower() or "wayland" in msg.lower():
                raise RuntimeError(f"Display capture failed: {msg}") from exc
            raise

    def _plan_action(self, goal: str, screenshot_bytes: bytes) -> ActionPlan:
        prompt = (
            "You are controlling a Linux desktop autonomously.\n"
            f"Goal: {goal}\n\n"
            "Return JSON only:\n"
            "{\n"
            '  "action": "click|type|press|hotkey|wait|open_url|launch_app|shell|finish|fail",\n'
            '  "target": "description of target element for click",\n'
            '  "text": "text to type",\n'
            '  "url": "https://... when action=open_url",\n'
            '  "app": "application command like xdg-open https://youtube.com or gnome-calculator",\n'
            '  "shell": "short safe shell command",\n'
            '  "key": "single key for press action",\n'
            '  "keys": ["ctrl", "l"],\n'
            '  "seconds": 1.0,\n'
            '  "reason": "brief reason"\n'
            "}\n"
            "Rules:\n"
            "- Prefer one atomic action at a time.\n"
            "- Use launch_app for opening calculator/browser and apps.\n"
            "- Use open_url after browser is ready.\n"
            "- Use finish only when goal is done.\n"
            "- Use fail if blocked.\n"
        )
        response = self._ask_vision(prompt, screenshot_bytes)
        payload = self._extract_json(response)
        return ActionPlan(
            action=str(payload.get("action", "fail")).strip().lower(),
            target=str(payload.get("target", "")).strip(),
            text=str(payload.get("text", "")).strip(),
            url=str(payload.get("url", "")).strip(),
            app=str(payload.get("app", "")).strip(),
            shell=str(payload.get("shell", "")).strip(),
            seconds=float(payload.get("seconds", 1.0) or 1.0),
            keys=[str(k).strip().lower() for k in (payload.get("keys") or []) if str(k).strip()],
            key=str(payload.get("key", "")).strip().lower(),
            reason=str(payload.get("reason", "")).strip(),
        )

    def _execute_action(
        self,
        plan: ActionPlan,
        screen_w: int,
        screen_h: int,
        screenshot_bytes: bytes,
    ) -> None:
        if plan.action == "click":
            if not plan.target:
                raise ValueError("Planner returned click action without target")
            box = self.analyzer.locate_element(screenshot_bytes, plan.target)
            self.automator.click_at_normalized_coords(
                box,
                screen_w,
                screen_h,
                delay=0.8,
                description=plan.target,
            )
            return

        if plan.action == "type":
            text = plan.text or ""
            self.automator.type_text_unicode(text, interval=0.03, delay=0.3)
            return

        if plan.action == "press":
            if not plan.key:
                raise ValueError("Planner returned press action without key")
            self.automator.press_key(plan.key)
            return

        if plan.action == "hotkey":
            if not plan.keys:
                raise ValueError("Planner returned hotkey action without keys")
            self.automator.send_hotkey(tuple(plan.keys))
            return

        if plan.action == "wait":
            time.sleep(max(0.2, min(plan.seconds, 10.0)))
            return

        if plan.action == "open_url":
            if not plan.url:
                raise ValueError("Planner returned open_url action without url")
            webbrowser.open(plan.url)
            self.runtime.add_log("info", f"Opened URL: {plan.url}")
            time.sleep(1.0)
            return

        if plan.action == "launch_app":
            if not plan.app:
                raise ValueError("Planner returned launch_app action without app command")
            subprocess.Popen(shlex.split(plan.app), stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
            self.runtime.add_log("info", f"Launched app: {plan.app}")
            time.sleep(1.2)
            return

        if plan.action == "shell":
            if not plan.shell:
                raise ValueError("Planner returned shell action without command")
            if self._is_blocked_shell(plan.shell):
                raise ValueError(f"Blocked potentially dangerous shell command: {plan.shell}")
            completed = subprocess.run(plan.shell, shell=True, capture_output=True, text=True, check=False)
            summary = (completed.stdout or completed.stderr or "").strip()[:400]
            self.runtime.add_log("info", f"Shell exit={completed.returncode} output={summary}")
            return

        if plan.action in {"finish", "fail"}:
            return

        raise ValueError(f"Unknown planner action: {plan.action}")

    def _is_blocked_shell(self, command: str) -> bool:
        blocked_tokens = [
            "rm -rf /",
            "mkfs",
            "shutdown",
            "reboot",
            "poweroff",
            "dd if=",
            "chmod -R 777 /",
            "kill -9 1",
        ]
        lowered = command.lower()
        return any(token in lowered for token in blocked_tokens)

    def _goal_is_met(self, goal: str, screenshot_bytes: bytes) -> bool:
        prompt = (
            "Determine whether the UI goal has been satisfied based on this screenshot.\n"
            f"Goal: {goal}\n"
            "Respond JSON only: {\"done\": true|false, \"reason\": \"brief reason\"}"
        )
        response = self._ask_vision(prompt, screenshot_bytes)
        payload = self._extract_json(response)
        done = bool(payload.get("done", False))
        self.runtime.add_log("info", f"Verification: done={done}")
        return done

    def _ask_vision(self, prompt: str, screenshot_bytes: bytes) -> str:
        image = Image.open(io.BytesIO(screenshot_bytes))
        response = self.analyzer.model.generate_content([prompt, image])
        maybe_raise = getattr(response, "raise_for_exception", None)
        if callable(maybe_raise):
            maybe_raise()
        return (response.text or "").strip()

    def _extract_json(self, text: str) -> Dict[str, Any]:
        match = re.search(r"\{.*\}", text, re.DOTALL)
        if not match:
            raise ValueError(f"Model did not return JSON: {text[:200]}")
        return json.loads(match.group(0))
